# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Qinwen Shi' Blog
description: "A coder and learner"
keywords: 'shiqinwen,blog,施勤文'
author:
  name: Qinwen Shi
  job_title: Programmer
  location: Shanghai
  email: qiwen.shi@gmail.com
  social_links:
    - name: facebook
      url: https://www.facebook.com/wen.shi.549
    - name: github
      url: https://github.com/qinwenshi
    - name: instagram
      url:
    - name: linkedin
      url: https://www.linkedin.com/in/wen-shi-6b189229/
    - name: stackoverflow
      url:
    - name: twitter
      url: https://twitter.com/shiqinwen
    - name: vk
      url:
home:
  section1: <h1>Wen Shi</h1>
  section2: <h2>A Coder and forever learner</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/qinwenshi/" title="Follow me on GitHub"></a></div>
blog:
  cc_license: # A link to CC License of your choice, e.g. http://creativecommons.org/licenses/by-sa/4.0/.
  cc_license_image: # An image of your CC License, e.g. /assets/images/theme/cc-by-sa.png
  footer_content: Shi Qinwen's Personal Website.

disqus:
  shortname: wenblog
  public_key: aKHyNODneMjnJkCWf3690NWbuAxAQ05GeprcoWyOZuP6EDp2g319NtPbvCgqqTEE
google_analytics: 73013332
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
